<?php
	$lang['lang']="bg";
	$lang['contacts']="Контакти";
	$lang['galeries']="Галерии";
	$lang['logo']="Лого";
	$lang['home_page']="Начало";
	$lang['projects']="Проекти";
	$lang['edit']="Редактиране";
	$lang['photos']="Снимки";
	$lang['addnew']="Добави нова игра";
	$lang['editalbum']="Редактиране на албум";
	$lang['no_name']="Липсва име";
	$lang['delete']="Изтриване";
	$lang['name']="Име";
	$lang['info']="Информация";
	$lang['info_pages']="Информационни страници";
	$lang['select']="Изберете";
	$lang['title']="Заглавие";
	$lang['short_info']="Кратка информация";
	$lang["please_fill_all_field"]="Всички полета са задължителни";
	$lang["make_main"]="Направи главна снимка";
	$lang["photos"]="Снимки";
	$lang["back"]="Назад";
	$lang["add_photo"]="Добави снимка";
	$lang["projects"]="Портфолио";
	$lang["about"]="За нас";
	$lang["service"]='Услуги';
	$lang["settings"]='Настройки';
	$lang["services"]='<span class="clr-1">У</span>слуги';
	$lang["send"]='Изпрати';
	$lang["val"]='Стойност';
	$lang["name"]='Име';
	$lang["email"]='Е-мейл';
	$lang["fullname"]='Име';
	$lang["subject"]='Тема';
	$lang["message"]='Съобщение';
	$lang["games"]='Игри';
	$lang["rules"]='Правила';
	$lang["armor"]='Екипировка';
	$lang["prices"]='Цени';
	$lang["gallery"]='Галерия';
	$lang["promo"]='Показвай на банера на играта';
	$lang["wrong_date"]="Некоректни данни";
	$lang["please_fill_all"]="Попълнете всички данни";
	$lang["logout"]="Изход";
	$lang["see_more"]="Вижте още снимки";
	$lang["description"]="Описание";
	$lang["paintball"]="Пейнтбол";
	$lang["leizartag"]="Лейзъртаг";
	$lang["bow"]="Лък";
	$lang["arbalet"]="Арбалет";
	$lang["gun"]="Пушка";
	$lang["off_road"]="Оф-роуд";
	$lang["barbeque"]="Барбекю";
	$lang["home"]="Начало";
	$lang["ask_from_site"]="Въпрос от:";
	
	
	
	
	
	
	
	
	
	
?>